/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    characters: Character;
    guilds: Guild;
    party_setups: PartySetup;
    reports_gl: ReportsGl;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    guilds: {
      characters: 'characters';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    guilds: GuildsSelect<false> | GuildsSelect<true>;
    party_setups: PartySetupsSelect<false> | PartySetupsSelect<true>;
    reports_gl: ReportsGlSelect<false> | ReportsGlSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'super_admin' | 'guild_master';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Data karakter ROOC dari berbagai Guild
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: string;
  name: string;
  job:
    | 'lord_knight'
    | 'paladin'
    | 'high_priest'
    | 'champion'
    | 'assassin_cross'
    | 'stalker'
    | 'high_wizard'
    | 'professor'
    | 'sniper'
    | 'minstrell'
    | 'gypsy'
    | 'mastersmith'
    | 'biochemist'
    | 'summoner'
    | 'adept_novice'
    | 'rebellion';
  guild_id: string | Guild;
  isVerified?: boolean | null;
  max_hp: number;
  patk?: number | null;
  matk?: number | null;
  pdef?: number | null;
  mdef?: number | null;
  refine_patk?: number | null;
  refine_matk?: number | null;
  refine_pdef?: number | null;
  refine_mdef?: number | null;
  hit?: number | null;
  flee?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  aspd?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  mspd?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  variable_cast?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  fixed_cast?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  healing_done?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  healing_taken?: number | null;
  critical?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  critical_damage?: number | null;
  critical_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  critical_damage_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  pdmg?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  mdmg?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  pdmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  mdmg_reduction?: number | null;
  ignore_pdef?: number | null;
  ignore_mdef?: number | null;
  pdmg_bonus?: number | null;
  mdmg_bonus?: number | null;
  pvp_dmg_bonus?: number | null;
  pvp_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  max_hp_percentage?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  equipment_patk_percentage?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  equipment_matk_percentage?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  equipment_pdef_percentage?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  equipment_mdef_percentage?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  dmg_vs_demi_human?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  dmg_reduction_demi_human?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  dmg_vs_medium?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  dmg_reduction_medium?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  neutral_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  neutral_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  fire_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  water_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  wind_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  earth_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  ghost_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  holy_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  fire_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  water_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  wind_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  earth_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  ghost_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  holy_dmg_reduction?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  poison_dmg_bonus?: number | null;
  /**
   * Contoh: 99.99 untuk 99.99%
   */
  poison_dmg_reduction?: number | null;
  pvp_score?: number | null;
  gl_reports?:
    | {
        report_id?: string | null;
        is_present?: boolean | null;
        actual_score?: number | null;
        party_assigned?: string | null;
        id?: string | null;
      }[]
    | null;
  gl_total_score?: number | null;
  gl_present_count?: number | null;
  gl_absent_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guilds".
 */
export interface Guild {
  id: string;
  name: string;
  guild_master: string | User;
  /**
   * Jumlah karakter terverifikasi dalam guild
   */
  total_characters?: number | null;
  /**
   * Akumulasi PvP score semua karakter terverifikasi
   */
  total_pvp_score?: number | null;
  gl_wins?: number | null;
  gl_losses?: number | null;
  gl_trends?: string | null;
  characters?: {
    docs?: (string | Character)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "party_setups".
 */
export interface PartySetup {
  id: string;
  guild_id: string | Guild;
  elite_parties?:
    | {
        party_name: string;
        slots?:
          | {
              required_job:
                | 'lord_knight'
                | 'paladin'
                | 'high_priest'
                | 'champion'
                | 'assassin_cross'
                | 'stalker'
                | 'high_wizard'
                | 'professor'
                | 'sniper'
                | 'minstrell'
                | 'gypsy'
                | 'mastersmith'
                | 'biochemist'
                | 'summoner'
                | 'adept_novice'
                | 'rebellion'
                | 'any';
              /**
               * Karakter yang terpilih otomatis atau di-assign manual
               */
              assigned_character?: (string | null) | Character;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sub_parties?:
    | {
        party_name: string;
        slots?:
          | {
              required_job:
                | 'lord_knight'
                | 'paladin'
                | 'high_priest'
                | 'champion'
                | 'assassin_cross'
                | 'stalker'
                | 'high_wizard'
                | 'professor'
                | 'sniper'
                | 'minstrell'
                | 'gypsy'
                | 'mastersmith'
                | 'biochemist'
                | 'summoner'
                | 'adept_novice'
                | 'rebellion'
                | 'any';
              assigned_character?: (string | null) | Character;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_gl".
 */
export interface ReportsGl {
  id: string;
  guild_id: string | Guild;
  report_name: string;
  match_status: 'win' | 'loss';
  match_score?: number | null;
  match_date?: string | null;
  member_reports?:
    | {
        character_id: string | Character;
        is_present?: boolean | null;
        actual_score?: number | null;
        party_assigned?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'characters';
        value: string | Character;
      } | null)
    | ({
        relationTo: 'guilds';
        value: string | Guild;
      } | null)
    | ({
        relationTo: 'party_setups';
        value: string | PartySetup;
      } | null)
    | ({
        relationTo: 'reports_gl';
        value: string | ReportsGl;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  job?: T;
  guild_id?: T;
  isVerified?: T;
  max_hp?: T;
  patk?: T;
  matk?: T;
  pdef?: T;
  mdef?: T;
  refine_patk?: T;
  refine_matk?: T;
  refine_pdef?: T;
  refine_mdef?: T;
  hit?: T;
  flee?: T;
  aspd?: T;
  mspd?: T;
  variable_cast?: T;
  fixed_cast?: T;
  healing_done?: T;
  healing_taken?: T;
  critical?: T;
  critical_damage?: T;
  critical_reduction?: T;
  critical_damage_reduction?: T;
  pdmg?: T;
  mdmg?: T;
  pdmg_reduction?: T;
  mdmg_reduction?: T;
  ignore_pdef?: T;
  ignore_mdef?: T;
  pdmg_bonus?: T;
  mdmg_bonus?: T;
  pvp_dmg_bonus?: T;
  pvp_dmg_reduction?: T;
  max_hp_percentage?: T;
  equipment_patk_percentage?: T;
  equipment_matk_percentage?: T;
  equipment_pdef_percentage?: T;
  equipment_mdef_percentage?: T;
  dmg_vs_demi_human?: T;
  dmg_reduction_demi_human?: T;
  dmg_vs_medium?: T;
  dmg_reduction_medium?: T;
  neutral_dmg_bonus?: T;
  neutral_dmg_reduction?: T;
  fire_dmg_bonus?: T;
  water_dmg_bonus?: T;
  wind_dmg_bonus?: T;
  earth_dmg_bonus?: T;
  ghost_dmg_bonus?: T;
  holy_dmg_bonus?: T;
  fire_dmg_reduction?: T;
  water_dmg_reduction?: T;
  wind_dmg_reduction?: T;
  earth_dmg_reduction?: T;
  ghost_dmg_reduction?: T;
  holy_dmg_reduction?: T;
  poison_dmg_bonus?: T;
  poison_dmg_reduction?: T;
  pvp_score?: T;
  gl_reports?:
    | T
    | {
        report_id?: T;
        is_present?: T;
        actual_score?: T;
        party_assigned?: T;
        id?: T;
      };
  gl_total_score?: T;
  gl_present_count?: T;
  gl_absent_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guilds_select".
 */
export interface GuildsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  guild_master?: T;
  total_characters?: T;
  total_pvp_score?: T;
  gl_wins?: T;
  gl_losses?: T;
  gl_trends?: T;
  characters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "party_setups_select".
 */
export interface PartySetupsSelect<T extends boolean = true> {
  id?: T;
  guild_id?: T;
  elite_parties?:
    | T
    | {
        party_name?: T;
        slots?:
          | T
          | {
              required_job?: T;
              assigned_character?: T;
              id?: T;
            };
        id?: T;
      };
  sub_parties?:
    | T
    | {
        party_name?: T;
        slots?:
          | T
          | {
              required_job?: T;
              assigned_character?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_gl_select".
 */
export interface ReportsGlSelect<T extends boolean = true> {
  id?: T;
  guild_id?: T;
  report_name?: T;
  match_status?: T;
  match_score?: T;
  match_date?: T;
  member_reports?:
    | T
    | {
        character_id?: T;
        is_present?: T;
        actual_score?: T;
        party_assigned?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}